### ISSUE TITLE
[前端技术]js实现一个简易旋转木马

### ISSUE THREAD

**Issue by weizhanzhan** [weizhanzhan/v_note#4]
### Html部分
``` html
 <div>
    <ul class="slider">
      <li class="list-item fl-1">a</li>
      <li class="list-item fl-2 left">b</li>    
      <li class="list-item fl-3 left">c</li>  
      <li class="list-item fl-3 right">d</li>
      <li class="list-item fl-2 right">e</li>
    </ul>
  </div>
 ```
### Javascript部分
``` js
 <script>
  ;(function(){
    var sliders =document.getElementsByClassName('slider')[0],
       sliderNodes = sliders.getElementsByClassName("list-item"),
       sliderArr = Array.from(sliderNodes),
       classes = []
       sliderArr.forEach(s => {
          classes.push(s.className)
       })
       setInterval(function(){
          classes.push(classes[0])
          classes.splice(0,1)
          classes.forEach((val,i)=>{
               sliderNodes[i].className=val
          })
       },2000)
  })()
 </script>
```
### Css
``` css
 <style>
  .slider {
    list-style: none;
    padding: 0;
    position: relative;
  }

  .list-item {
    position: absolute;
    background: blue;
    width: 100px;
    height: 50px;
    color: aliceblue;
    text-align: center;
    line-height: 50px;
    transition: all 2s cubic-bezier(0.3, 0.5, 0.1, .9);
    box-shadow:0px 1px 2px #6B6B6B;
  }
  .list-item.fl-1 {
    top: 300px;
    left: 50%;
  }
  .list-item.fl-2.left {
    top: 200px;
    left: 30%;
  }
  .list-item.fl-2.right {
    top: 200px;
    left: 70%;
  }
  .list-item.fl-3.left {
    top: 100px;
    left: 40%;
  }
  .list-item.fl-3.right {
    top: 100px;
    left: 60%;
  }

 </style>
```
欢迎指导~
