### ISSUE TITLE
[前端技术]css 实现垂直居中的一些方案

### ISSUE THREAD

**Issue by weizhanzhan** [weizhanzhan/v_note#7]
```css
.box{
  width:100px;
  height:100px;
}
.box1{
  display: table-cell;
  vertical-align: middle;
  text-align: center;
  background:red
}
.box2{
  display:flex;
  align-items:center;
  justify-content:center;
  background:blue
}
.box3{
  padding:35px 0;
  text-align:center;
  background:green;
  box-sizing: border-box
}
.box4{
  background:#eee;
  position:relative
}
.box4 span{
  position: absolute;
  top:50%;
  left:50%;
  width:100%;
  transform:translate(-50%,-50%);
  text-align: center;
}
```
